#!/bin/bash 
HIPSYCL_PKG_LLVM_REPO_BRANCH=${HIPSYCL_PKG_LLVM_REPO_BRANCH:-release/9.x}
export INSTALL_PREFIX=${INSTALL_PREFIX:-/opt/hipSYCL}

set -e
HIPSYCL_PKG_BUILD_DIR=$HOME/git/llvm-vanilla
rm -rf $HIPSYCL_PKG_BUILD_DIR


case $HIPSYCL_PKG_LLVM_REPO_BRANCH in

	release/9.x)
		echo "Cloning LLVM $HIPSYCL_PKG_LLVM_REPO_BRANCH"	
		git clone -b $HIPSYCL_PKG_LLVM_REPO_BRANCH https://github.com/llvm/llvm-project $HIPSYCL_PKG_BUILD_DIR
		sed -i 's/CHECK_SIZE_AND_OFFSET(ipc_perm, mode);//g' $HIPSYCL_PKG_BUILD_DIR/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc
		;;

	release/10.x)
		echo "Cloning LLVM $HIPSYCL_PKG_LLVM_REPO_BRANCH"	
		git clone -b $HIPSYCL_PKG_LLVM_REPO_BRANCH https://github.com/llvm/llvm-project $HIPSYCL_PKG_BUILD_DIR
		;;
	
	*)
		echo "LLVM version $HIPSYCL_PKG_LLVM_REPO_BRANCH is not supported"
		exit -1
		;;
esac
		

export CC=${HIPSYCL_BASE_CC:-clang}
export CXX=${HIPSYCL_BASE_CXX:-clang++}
export HIPSYCL_PKG_BUILD_TYPE=Release
export LLVM_INSTALL_PREFIX=$INSTALL_PREFIX/llvm
export TARGETS_TO_HIPSYCL_PKG_BUILD="AMDGPU;NVPTX;X86"
export NUMTHREADS=`nproc`

CMAKE_OPTIONS="-DLLVM_ENABLE_PROJECTS=clang;compiler-rt;lld;openmp -DOPENMP_ENABLE_LIBOMPTARGET=OFF -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_HIPSYCL_PKG_BUILD_TYPE=$HIPSYCL_PKG_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$LLVM_INSTALL_PREFIX -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_TARGETS_TO_HIPSYCL_PKG_BUILD=$TARGETS_TO_HIPSYCL_PKG_BUILD -DCLANG_ANALYZER_ENABLE_Z3_SOLVER=0 -DLLVM_INCLUDE_BENCHMARKS=0 -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DCMAKE_INSTALL_RPATH=$INSTALL_PREFIX/lib -DLLVM_ENABLE_OCAMLDOC=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON -DLLVM_ENABLE_DUMP=ON"

mkdir -p $HIPSYCL_PKG_BUILD_DIR/build
cd $HIPSYCL_PKG_BUILD_DIR/build
cmake $CMAKE_OPTIONS $HIPSYCL_PKG_BUILD_DIR/llvm
make -j $NUMTHREADS
make install
cp -p $HIPSYCL_PKG_BUILD_DIR/build/bin/llvm-lit   $LLVM_INSTALL_PREFIX/bin/llvm-lit
cp -p $HIPSYCL_PKG_BUILD_DIR/build/bin/FileCheck  $LLVM_INSTALL_PREFIX/bin/FileCheck
cp -p $HIPSYCL_PKG_BUILD_DIR/build/bin/count      $LLVM_INSTALL_PREFIX/bin/count
cp -p $HIPSYCL_PKG_BUILD_DIR/build/bin/not        $LLVM_INSTALL_PREFIX/bin/not
cp -p $HIPSYCL_PKG_BUILD_DIR/build/bin/yaml-bench $LLVM_INSTALL_PREFIX/yaml-bench
